name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build -- --sourceMap false
      - name: List directory contents
        run: ls -la .
      - name: Set up containers
        run: docker compose up rabbitmq minio postgresql -d --build
      - name: Wait a moment for containers to properly start
        run: sleep 10
      - name: Run tests
        run: npm run test -- --coverage=false --verbose=false -o
        env:
          APP_NAME: "test"
          NODE_ENV: "test"
          PORT: 8080
      - name: Tear down containers
        run: docker compose down
      # - name: Run tests
      #   run: |
      #     docker compose --env-file "" up rabbitmq minio postgresql --build -d
      #     sleep 10
      #     npm run test -- --coverage=false --verbose=false -o
      #     docker compose down
      #   env:
      #     APP_NAME: "test"
      #     NODE_ENV: "test"
      #     PORT: 8080
