name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build -- --sourceMap false
      - name: Run tests
        run: |
          docker compose up rabbitmq minio postgresql -d --build
          sleep 10
          npm run test -- --coverage=false --verbose=false
          docker compose down
        env:
          APP_NAME: "test"
          NODE_ENV: "test"
          PORT: 8080
